exercises translated 73-80
4GeeksAcademy/master-python-programming-exercises pull request #15
Opened 2021-05-04 17:09 UTC by ElviraQDP

translation added

2021-06-29 17:50 UTC, alesanchezr approved these changes

2021-08-02 19:22 UTC, alesanchezr requested changes

2021-08-02 19:22 UTC, alesanchezr commented on exercises/116-Eight queens/README.md
> +## 📝 Instrucciones:
this should be english.

2021-08-02 19:22 UTC, alesanchezr commented on exercises/120-Diagonals/README_copy.md
> +## 📝 Instructions:
the file name is wrong. `_copy??`

2021-08-02 19:22 UTC, alesanchezr commented on exercises/122-Swap columns/README.es.md
> + # `122` Intercambia columnas
exercise folder is wrong, there should be no spaces: `122-Swap-Columns` instead of `122-Swap Columns`

2021-08-02 19:22 UTC, alesanchezr commented on exercises/125-Number of distinct/README.es.md
> + # `125` Cantidad de números distintos
Remove spaces from file name

2021-08-02 19:22 UTC, alesanchezr commented on exercises/126-Number of common/README.es.md
> + # `126` Números en común
Remove spaces from file name

2021-08-02 19:22 UTC, alesanchezr commented on exercises/128-Seen before/README.es.md
> + # `128` Seen before
remove spaces from file name

2021-08-02 19:22 UTC, alesanchezr commented on exercises/071-Sum of N numbers/README.es.md
> +# `71` La suma de N números
remove spaces from file name, should be `071-Sum-of-N-numbers` instead of `071-Sum of N numbers`

2021-08-02 19:22 UTC, alesanchezr commented on exercises/072-Sum of cubes/README.es.md
> +# `72` Suma de cubos
File name is wrong, replace spaces with `-`

2021-08-02 19:22 UTC, alesanchezr commented on exercises/073-Number of zeros/README.es.md
> +# `73` Cantidad de 0
File name is wrong, replace spaces with `-`

2021-08-02 19:22 UTC, alesanchezr commented on exercises/074-Sum of factorials/README.es.md
> +# `74` Suma de factoriales
File name is wrong, replace spaces with `-`

2021-08-02 20:50 UTC, ElviraQDP commented on exercises/128-Seen before/README.es.md
> + # `128` Seen before
no spaces

2023-04-07 19:58 UTC, closed without merging