codespaces reference
4GeeksAcademy/master-python-programming-exercises pull request #49
Opened 2023-04-14 12:25 UTC by Lorenagubaira

2023-04-19 21:14 UTC, tommygonzaleza requested changes

2023-04-19 21:14 UTC, tommygonzaleza commented on README.es.md
> +Puedes empezar estos ejercicios en pocos segundos haciendo clic en: [Abrir en Codespaces](https://codespaces.new/?repo=4GeeksAcademy/css-layouts-tutorial-exercises) (recomendado) o [Abrir en Gitpod](
El link del repositorio tiene el de css

2023-04-27 21:43 UTC, tommygonzaleza approved these changes

2023-05-01 13:51 UTC, alesanchezr approved these changes

2023-05-01 13:51 UTC, merged