exercises 28-sequence-of-lines to 34-a-aa-aaa-aaaa
4GeeksAcademy/master-python-programming-exercises pull request #58
Opened 2023-12-20 11:49 UTC by josemoracard

2023-12-20 18:09 UTC, tommygonzaleza requested changes

2023-12-20 18:09 UTC, tommygonzaleza commented on exercises/31-sum-eigth-digit/README.es.md
> +# `31` Sum eight digit
Cambia el nombre de la funcion, no esta relacionado con lo que se pide hacer

2023-12-20 18:09 UTC, tommygonzaleza commented on exercises/32-numbers-of-letters-and-digits/README.es.md
> +letters_and_digits(hello world! 123)
Esto es un error de sintaxis

2023-12-20 18:09 UTC, tommygonzaleza commented on exercises/34-a_aa_aaa_aaaa/solution.hide.py
>  def computed_value(param):
Pon otra solucion mas parecida a lo que haria un estudiante

2023-12-20 18:30 UTC, josemoracard commented on exercises/29-remove-duplicate-words/README.md
> +1. Write a function called `remove_duplicate_words()` that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanume
done

2023-12-20 18:55 UTC, josemoracard commented on exercises/30-divisable-binary/README.es.md
> +## 📎 Ejemplo de salida:
done

2023-12-20 19:15 UTC, josemoracard commented on exercises/31-sum-eigth-digit/README.es.md
> +# `31` Sum eight digit
done

2023-12-20 19:19 UTC, josemoracard commented on exercises/32-numbers-of-letters-and-digits/README.es.md
> +letters_and_digits(hello world! 123)
done

2023-12-20 19:28 UTC, josemoracard commented on exercises/34-a_aa_aaa_aaaa/solution.hide.py
>  def computed_value(param):
done

2024-01-24 13:52 UTC, tommygonzaleza approved these changes

2024-01-24 15:44 UTC, merged