exercises 35-square-each-odd-number to 41-frequency-of-words
4GeeksAcademy/master-python-programming-exercises pull request #59
Opened 2023-12-20 16:47 UTC by josemoracard

2023-12-20 19:24 UTC, tommygonzaleza requested changes

2023-12-20 19:24 UTC, tommygonzaleza commented on exercises/38-sort-tuples-ascending/README.md
> +sort_tuples_ascending("Tom,19,80 John,20,90 Jony,17,91 Jony,17,93 Jason,21,85")
Mejor que reciba una lista de strings

2023-12-20 19:24 UTC, tommygonzaleza commented on exercises/39-class-that-iterates/README.md
> +# `39` Class that iterates
Agrega explicacion de generator functions y del yield

2023-12-20 19:24 UTC, tommygonzaleza commented on exercises/40-compute-robot-distance/README.es.md
> +## 📝 Instrucciones:
Debe recibir una lista de strings

2023-12-20 19:24 UTC, tommygonzaleza commented on exercises/41-frequency-of-words/README.es.md
> +"New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3."
Falta el solution y agregar unos hints que expliquen un poco lo que deben utilizar para solucionarlo (metodos)

2024-01-01 01:21 UTC, josemoracard commented on exercises/35-square-each-odd-number/solution.hide.py
> +def square_odd_numbers(numbers):
done

2024-01-01 02:14 UTC, josemoracard commented on exercises/37-validity-of-password/README.es.md
> +Tu programa debería aceptar una secuencia de contraseñas separadas por comas y verificarlas según los criterios anteriores. Las contraseñas que cumplan con los criterios deben imprimirse, cada una se
done

2024-01-01 02:40 UTC, josemoracard commented on exercises/38-sort-tuples-ascending/README.md
> +sort_tuples_ascending("Tom,19,80 John,20,90 Jony,17,91 Jony,17,93 Jason,21,85")
done

2024-01-01 03:36 UTC, josemoracard commented on exercises/39-class-that-iterates/README.md
> +# `39` Class that iterates
generator functions y yield no son un concepto que se pueda explicar sin llenar el README de demasiado texto.

se ha referido a un articulo en el hint

2024-01-01 04:31 UTC, josemoracard commented on exercises/40-compute-robot-distance/README.es.md
> +## 📝 Instrucciones:
done

2024-01-05 15:37 UTC, josemoracard commented on exercises/41-frequency-of-words/README.es.md
> +"New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3."
hecho, falta que el test cuadre con el solution

2024-01-11 23:05 UTC, tommygonzaleza commented on exercises/37-validity-of-password/README.es.md
> +Tu programa debería aceptar una secuencia de contraseñas separadas por comas y verificarlas según los criterios anteriores. Las contraseñas que cumplan con los criterios deben imprimirse, cada una se
Acomodar regular expression del solution. La regular expression debe encargarse de chequear si no obtiene alguno de los caracteres validos (Sin separarlo en grupos diferentes). Debes dejar una unica solucion.

2024-01-11 23:09 UTC, tommygonzaleza approved these changes

2024-01-17 16:30 UTC, josemoracard commented on exercises/37-validity-of-password/README.es.md
> +Tu programa debería aceptar una secuencia de contraseñas separadas por comas y verificarlas según los criterios anteriores. Las contraseñas que cumplan con los criterios deben imprimirse, cada una se
done

2024-01-17 18:46 UTC, tommygonzaleza approved these changes

2024-01-24 15:24 UTC, merged