Añadir ejercicio 042-understanding_classes
4GeeksAcademy/master-python-programming-exercises pull request #61
Opened 2024-01-02 03:38 UTC by josemoracard

2024-01-17 20:03 UTC, tommygonzaleza requested changes

2024-01-17 20:03 UTC, tommygonzaleza commented on exercises/042-understanding_classes/README.es.md
> +student1.introduce()
Agregar print(student1.introduce())

2024-01-17 20:03 UTC, tommygonzaleza commented on exercises/042-understanding_classes/README.es.md
> +student1.study(3)
Agregar print(student1.study(3))

2024-01-17 20:03 UTC, tommygonzaleza commented on exercises/042-understanding_classes/README.es.md
> +        print(f"After studying, {self.name}'s new grade is {self.grade}.")
Quita todos los print, y reemplazalo por un unico return que retorne:

`return f"After studying for {hours} hours, {self.name}'s new grade is {self.grade}."`

2024-01-17 20:03 UTC, tommygonzaleza commented on exercises/042-understanding_classes/README.md
> +class Student:
Agregar los cambios que se pidieron en el readme en español

2024-01-17 20:03 UTC, tommygonzaleza commented
- [ ] Agregar tests con ChatGPT, debes validar:
    - La clase `Student` existe
    - La clase `Student` tiene el atributo `name`.
    - La clase `Student` tiene el atributo `age`.
    - La clase `Student` tiene el atributo `grade`.
    - La clase `Student` tiene el metodo `introduce`.
    - El metodo `introduce` retorna el string esperado (Valida en el mismo test con dos escenarios).
    - La clase `Student` tiene el metodo `study`.
    - El metodo `study` retorna el string esperado (Valida en el mismo test con dos escenarios).

2024-01-23 23:44 UTC, josemoracard commented on exercises/042-understanding_classes/README.es.md
> +student1.introduce()
done

2024-01-23 23:44 UTC, josemoracard commented on exercises/042-understanding_classes/README.es.md
> +student1.study(3)
done

2024-01-23 23:45 UTC, josemoracard commented on exercises/042-understanding_classes/README.es.md
> +        print(f"After studying, {self.name}'s new grade is {self.grade}.")
done

2024-01-23 23:45 UTC, josemoracard commented on exercises/042-understanding_classes/README.md
> +class Student:
done

2024-01-24 13:36 UTC, tommygonzaleza approved these changes

2024-01-24 15:45 UTC, merged