Añadir ejercicio 043-inheritance_and_polymorphism
4GeeksAcademy/master-python-programming-exercises pull request #62
Opened 2024-01-03 03:18 UTC by josemoracard

2024-01-17 20:15 UTC, tommygonzaleza commented
- [ ] Agregar tests con ChatGPT, para que valide:
    - La clase CollegeStudent existe
    - La clase CollegeStudent tiene el atributo name.
    - La clase CollegeStudent tiene el atributo age.
    - La clase CollegeStudent tiene el atributo grade.
    - La clase CollegeStudent tiene el atributo major.
    - La clase CollegeStudent tiene el metodo introduce.
    - El metodo introduce retorna el string esperado (Valida en el mismo test con dos escenarios).
    - La clase CollegeStudent tiene el metodo study.
    - El metodo study retorna el string esperado (Valida en el mismo test con dos escenarios).
    - La clase CollegeStudent tiene el metodo attend_lecture.
    - El metodo attend_lecture retorna el string esperado (Valida en el mismo test con dos escenarios).
    -  Agregar solution, que basicamente es el codigo del readme

2024-01-17 20:17 UTC, tommygonzaleza requested changes

2024-01-17 20:17 UTC, tommygonzaleza commented on exercises/043-inheritance_and_polymorphism/README.es.md
> +        print(f"{self.name} is a high school student specializing in {self.specialization} and is studying for {hours} hours for exams.")
Cambiar `print` por `return`

2024-01-17 20:17 UTC, tommygonzaleza commented on exercises/043-inheritance_and_polymorphism/README.es.md
> +3. Modifica el método heredado `introduce` para imprimir este string:
Para ~imprimir~ retornar este string

2024-01-17 20:17 UTC, tommygonzaleza commented on exercises/043-inheritance_and_polymorphism/README.md
> +# `043` inheritance and polymorphism
Hacer los mismos cambios que en español

2024-01-17 20:17 UTC, tommygonzaleza commented on exercises/043-inheritance_and_polymorphism/README.es.md
> +# `043` inheritance and polymorphism
Poner Inheritance con I mayuscula

2024-01-17 20:17 UTC, tommygonzaleza commented on exercises/043-inheritance_and_polymorphism/solution.hide.py
> +        print(f"Hi there! I'm {self.name}, a college student majoring in {self.major}.")
Cambiar print por return

2024-01-17 20:17 UTC, tommygonzaleza commented on exercises/043-inheritance_and_polymorphism/solution.hide.py
> +        print(f"{self.name} is studying for {hours} hours.")
Cambiar print por return

2024-01-17 20:17 UTC, tommygonzaleza commented on exercises/043-inheritance_and_polymorphism/solution.hide.py
> +        print(f"Hello! I am {self.name}, I am {self.age} years old, and my current grade is {self.grade}.")
Cambiar print por return

2024-01-17 20:17 UTC, tommygonzaleza commented on exercises/043-inheritance_and_polymorphism/solution.hide.py
> +        print(f"{self.name} is attending a lecture for {self.major} students.")
Cambiar print por return

2024-01-17 20:17 UTC, tommygonzaleza commented on exercises/043-inheritance_and_polymorphism/solution.hide.py
> +college_student.study(3)
Agregar print

2024-01-24 02:16 UTC, josemoracard commented on exercises/043-inheritance_and_polymorphism/README.es.md
> +        print(f"{self.name} is a high school student specializing in {self.specialization} and is studying for {hours} hours for exams.")
done

2024-01-24 02:16 UTC, josemoracard commented on exercises/043-inheritance_and_polymorphism/README.es.md
> +3. Modifica el método heredado `introduce` para imprimir este string:
done

2024-01-24 02:16 UTC, josemoracard commented on exercises/043-inheritance_and_polymorphism/README.md
> +# `043` inheritance and polymorphism
done

2024-01-24 02:16 UTC, josemoracard commented on exercises/043-inheritance_and_polymorphism/README.es.md
> +# `043` inheritance and polymorphism
done

2024-01-24 02:16 UTC, josemoracard commented on exercises/043-inheritance_and_polymorphism/solution.hide.py
> +        print(f"Hi there! I'm {self.name}, a college student majoring in {self.major}.")
done

2024-01-24 02:16 UTC, josemoracard commented on exercises/043-inheritance_and_polymorphism/solution.hide.py
> +        print(f"{self.name} is studying for {hours} hours.")
done

2024-01-24 02:17 UTC, josemoracard commented on exercises/043-inheritance_and_polymorphism/solution.hide.py
> +        print(f"Hello! I am {self.name}, I am {self.age} years old, and my current grade is {self.grade}.")
done

2024-01-24 02:18 UTC, josemoracard commented on exercises/043-inheritance_and_polymorphism/solution.hide.py
> +        print(f"{self.name} is attending a lecture for {self.major} students.")
done

2024-01-24 13:43 UTC, tommygonzaleza approved these changes

2024-01-24 15:44 UTC, merged