Añadir ejercicio 044-static_and_class_method
4GeeksAcademy/master-python-programming-exercises pull request #63
Opened 2024-01-03 12:35 UTC by josemoracard

2024-01-17 20:29 UTC, tommygonzaleza requested changes

2024-01-17 20:29 UTC, tommygonzaleza commented on exercises/044-static_and_class_methods/README.es.md
> +# `044` static and class methods
Crear un ejercicio para static methods y otro para class methods. Las instrucciones las mantienes tal como estan, en el primer ejercicio, el segundo por ser una continuacion solo explicas lo del segundo.

2024-01-17 20:29 UTC, tommygonzaleza commented on exercises/044-static_and_class_methods/README.es.md
> +# `044` static and class methods
Las instrucciones del ejercicio si deben incluir solo las que estan relacionadas con la clase del ejercicio

2024-01-17 20:29 UTC, tommygonzaleza commented on exercises/044-static_and_class_methods/README.md
> +# `044` static and class methods
Agrega los mismos cambios que te puse en el de español

2024-01-24 12:30 UTC, josemoracard commented on exercises/044-static_and_class_methods/README.es.md
> +# `044` static and class methods
done

2024-01-24 12:30 UTC, josemoracard commented on exercises/044-static_and_class_methods/README.md
> +# `044` static and class methods
done

2024-01-24 19:25 UTC, tommygonzaleza commented
- [ ] Agregar otro test con numeros diferentes

2024-02-14 14:38 UTC, merged